# Conclusion

The dataset “Asian American Quality of Life” was analyzed through the exploration of various graphs. The project looked into contentment with a life of quality, expectations for the near future, challenges, and worries. The key takeaways are as follows: it is not completely necessary to remove all NA values and then start the analysis, the feature columns that are being plotted can be analyzed for missing values and transformed accordingly to get a clean neat graph that gives perfect insight; Every plot should have significance and be worthwhile; Working with categorical data can be challenging, particularly when there are no continuous number factors. There aren’t many options to plot the data, data cleaning and bringing it to the right format takes more time. The right order of plotting considering the dependent and independent variables, the categories to plot and their order really matters. 

From the analysis of data, it can be observed that Austin Texas as a whole is a good place to live in and many respondents feel the quality of life here is better to excellent. There were a number of observations some of which are as follows: 

* Different age groups have the maximum population from different ethnic groups, which shows that there is a mixed set of people in Austin, Texas.  
* People who live close to their blood relatives typically have excellent or very good mental health, however the age group they belong to certainly influences this. 
* The percentage of US citizens with salaries of $70,000 or more is higher among those who were born in the US, and they also tend to have more years of residency on average than non-citizens.
* Austin is a good place in terms of a place to live and work but some believe that it lacks strong art and culture scene and isn't a suitable place to retire. 
* There are different age group of people but most married and singles prefer to stay in their own one-family house or a rented Apartment/ Townhouse/ Condominium. 
* Among those with family, friends and acquaintances the ones with family seem to the most satisfied under males and females. 
* The majority of people who experience any mental health concern look for a general practitioner's help. 
* Discrimination is not observed much in this place. 
* The majority of responders have problems with hypertension, and it is evident that almost all of them have insurance, allowing utilizing the services offered. 
* Only a tiny minority of those with insurance do not consider physical check-up, yet the majority regularly check their health. 

With a number of facilities & amenities, answering various sociodemographic information, immigration, health status, use of health services, family and social resources, emotional well-being and quality of life, neighborhood and community resources, and awareness of/utilization of/satisfaction with city services Austin, Texas is a good place as mentioned earlier. 

Working with survey data especially a categorical one made our team realize the importance of cleaning and getting the right insight. Not every graph is suitable for every set of data, some information can be represented only using certain graphs. The skill of analysis, storytelling, exploration and visualization is essential for a data scientist. Through this project, we learned not just r, but the art of deriving insights and storytelling. The right questions to be asked for a deeper understanding of how things work to enable predictive abilities thus making us confident to work on any real-world data.

